# Generated by Django 5.1.2 on 2024-11-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELEVERED'), (4, 'ORDER_REJECTED'), (1, 'ORDER_CONFIRMED')], default=0),
        ),
    ]
